package com.data3000.admin.bd;

// Generated 12/01/2014 11:11:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.data3000.admin.vo.Formulario;
import com.data3000.admin.vo.Menu;

/**
 * PltMenu generated by hbm2java
 */
public class PltMenu implements Menu, java.io.Serializable {

	private long menuIdn;
	private PltMenu pltMenu;
	private PltFormulario pltFormulario;
	private int menuOrden;
	private String menuNombre;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<PltMenu> pltMenus = new HashSet<PltMenu>(0);

	public PltMenu() {
	}

	public PltMenu(long menuIdn, String menuNombre, int menuOrden, String audiUsuario,	Date audiFechModi, boolean audiSiAnul) {
		this.menuIdn = menuIdn;
		this.menuNombre = menuNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.menuOrden = menuOrden;
	}

	public PltMenu(long menuIdn, PltMenu pltMenu, PltFormulario pltFormulario, int menuOrden,
			String menuNombre, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<PltMenu> pltMenus) {
		this.menuIdn = menuIdn;
		this.pltMenu = pltMenu;
		this.pltFormulario = pltFormulario;
		this.menuNombre = menuNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.pltMenus = pltMenus;
		this.menuOrden = menuOrden;
	}

	public long getMenuIdn() {
		return this.menuIdn;
	}

	public void setMenuIdn(long menuIdn) {
		this.menuIdn = menuIdn;
	}

	public PltMenu getPltMenu() {
		return this.pltMenu;
	}

	public void setPltMenu(PltMenu pltMenu) {
		this.pltMenu = pltMenu;
	}

	public PltFormulario getPltFormulario() {
		return this.pltFormulario;
	}

	public void setPltFormulario(PltFormulario pltFormulario) {
		this.pltFormulario = pltFormulario;
	}

	public String getMenuNombre() {
		return this.menuNombre;
	}

	public void setMenuNombre(String menuNombre) {
		this.menuNombre = menuNombre;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<PltMenu> getPltMenus() {
		return this.pltMenus;
	}

	public void setPltMenus(Set<PltMenu> pltMenus) {
		this.pltMenus = pltMenus;
	}

	@Override
	public String getNombre() {		
		return getMenuNombre();
	}

	@Override
	public Formulario getFormulario() {
		return getPltFormulario();
	}

	@Override
	public Menu getPadre() {
		return getPltMenu();
	}

	public int getMenuOrden() {
		return menuOrden;
	}

	public void setMenuOrden(int menuOrden) {
		this.menuOrden = menuOrden;
	}
	
	

}
