package com.data3000.admin.bd;

// Generated 12/01/2014 11:11:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PltPermiso generated by hbm2java
 */
public class PltPermiso implements java.io.Serializable {

	private long permIdn;
	private PltRol pltRol;
	private PltFormulario pltFormulario;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public PltPermiso() {
	}

	public PltPermiso(long permIdn, PltRol pltRol, PltFormulario pltFormulario,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.permIdn = permIdn;
		this.pltRol = pltRol;
		this.pltFormulario = pltFormulario;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public PltPermiso(long permIdn, PltRol pltRol, PltFormulario pltFormulario,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul,
			String audiMotiAnul, String audiChecksum) {
		this.permIdn = permIdn;
		this.pltRol = pltRol;
		this.pltFormulario = pltFormulario;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getPermIdn() {
		return this.permIdn;
	}

	public void setPermIdn(long permIdn) {
		this.permIdn = permIdn;
	}

	public PltRol getPltRol() {
		return this.pltRol;
	}

	public void setPltRol(PltRol pltRol) {
		this.pltRol = pltRol;
	}

	public PltFormulario getPltFormulario() {
		return this.pltFormulario;
	}

	public void setPltFormulario(PltFormulario pltFormulario) {
		this.pltFormulario = pltFormulario;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

}
