package com.data3000.admin.bd;

// Generated 12/01/2014 11:11:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PltRelaForm generated by hbm2java
 */
public class PltRelaForm implements java.io.Serializable {

	private long relaFormIdn;
	private PltFormulario pltFormularioByFormHijo;
	private PltFormulario pltFormularioByFormPadre;
	private short relaFormOrden;
	private String relaFormTipo;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public PltRelaForm() {
	}

	public PltRelaForm(long relaFormIdn, PltFormulario pltFormularioByFormHijo,
			PltFormulario pltFormularioByFormPadre, short relaFormOrden,
			String relaFormTipo, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.relaFormIdn = relaFormIdn;
		this.pltFormularioByFormHijo = pltFormularioByFormHijo;
		this.pltFormularioByFormPadre = pltFormularioByFormPadre;
		this.relaFormOrden = relaFormOrden;
		this.relaFormTipo = relaFormTipo;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public PltRelaForm(long relaFormIdn, PltFormulario pltFormularioByFormHijo,
			PltFormulario pltFormularioByFormPadre, short relaFormOrden,
			String relaFormTipo, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum) {
		this.relaFormIdn = relaFormIdn;
		this.pltFormularioByFormHijo = pltFormularioByFormHijo;
		this.pltFormularioByFormPadre = pltFormularioByFormPadre;
		this.relaFormOrden = relaFormOrden;
		this.relaFormTipo = relaFormTipo;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getRelaFormIdn() {
		return this.relaFormIdn;
	}

	public void setRelaFormIdn(long relaFormIdn) {
		this.relaFormIdn = relaFormIdn;
	}

	public PltFormulario getPltFormularioByFormHijo() {
		return this.pltFormularioByFormHijo;
	}

	public void setPltFormularioByFormHijo(PltFormulario pltFormularioByFormHijo) {
		this.pltFormularioByFormHijo = pltFormularioByFormHijo;
	}

	public PltFormulario getPltFormularioByFormPadre() {
		return this.pltFormularioByFormPadre;
	}

	public void setPltFormularioByFormPadre(
			PltFormulario pltFormularioByFormPadre) {
		this.pltFormularioByFormPadre = pltFormularioByFormPadre;
	}

	public short getRelaFormOrden() {
		return this.relaFormOrden;
	}

	public void setRelaFormOrden(short relaFormOrden) {
		this.relaFormOrden = relaFormOrden;
	}

	public String getRelaFormTipo() {
		return this.relaFormTipo;
	}

	public void setRelaFormTipo(String relaFormTipo) {
		this.relaFormTipo = relaFormTipo;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

}
